spring:
    datasource:
        url: ${DESARROLLO_DATASOURCE_URL}
        username: ${DESARROLLO_DATASOURCE_USER}
        password: ${DESARROLLO_DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

files:
  basePath: C:/Users/jaibe/Documents/SED/SED-BACKEND/src/main/java/co/edu/unicauca/sed/archivos
