spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: SEDOCENTE
  datasource:
    url: ${DESARROLLO_DATASOURCE_URL}
    username: ${DESARROLLO_DATASOURCE_USER}
    password: ${DESARROLLO_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  notification:
    service:
      url: ${NOTIFICATION_SERVICE_URL}
  periodo-academico:
    api:
      url: ${PERIODO_ACADEMICO_API_URL}

files:
  basePath: ${FILES_BASE_PATH}
document:
  upload-dir: ${DOCUMENT_UPLOAD_DIR}

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    'co.edu.unicauca.sed.api': ${LOG_LEVEL_API}
  file:
    name: ${LOG_FILE_NAME}
    max-size: ${LOG_FILE_MAX_SIZE}
    max-history: ${LOG_FILE_MAX_HISTORY}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
